version: "1.0.2"

services:
  main:
    container_name: main-app
    restart: always
    build: .
    env_file: .env
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3000:3000

  worker:
    container_name: worker
    restart: always
    build: worker
    depends_on:
      - rabbitmq
      - main

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672
      - 5672:5672
