version: "1.0.2"

services:
  main:
    container_name: main-app
    build: .
    env_file: .env
    depends_on:
     - postgres
    ports:
      - 3000:3000

  postgres:
   image: postgres:alpine
   environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: postgres
   expose:
     - 5432