version: "1.0.2"

services:
  api:
    container_name: api
    restart: always
    build: api
    env_file: .env
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3000:3000

  worker:
    container_name: worker
    restart: always
    build: worker
    env_file: .env
    volumes:
      - ./worker:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672
      - 5672:5672
